### ISSUE TITLE
Reporting V3 Epic

### ISSUE THREAD

**Issue by anthony-sarkis** [diffgram/diffgram#1162]
Existing reporting issues are tagged here
https://github.com/diffgram/diffgram/labels/reporting

Other issues I'll bullet point here to group together

- [ ] The by user drill down module is missing from Insights panel
- [ ] The difference between the Insights (per job) reporting, and the global reporting feels ill-defined. I think the technical side here doesn't need much work, more just documenting how it flows, like that one's "pre-filtered" to a specific view etc
- [ ] Documenting new dedicated reports. We have a variety of newish dedicated reports (like annotator performance, approve/reject etc). These are all good but just need to document them better. Each report maybe has it's own page briefly explaining the purpose behind it, what it includes/doesn't include, etc. It's one of those things that's obvious when we make it, but then time goes by. 

Please feel free to add other ideas on improving reporting and analytics
