### ISSUE TITLE
Migration Tool Planning / Known Caveats Tracking

### ISSUE THREAD

**Issue by anthony-sarkis** [diffgram/diffgram#896]
### Ideas
- [ ] Cancel option
- [ ] List page schema link
- [ ] Preview, show file and instance counts
- [ ] Continue to expand recently added HTTP logs pattern.  Server logs are not very useful for end user etc... 
Should copy all existing relevant logs to that http log artifice we have so user can easily see
Also can help if say export gets stopped suddenly
- [ ] Graceful shut down consideration
- [ ] Multithreading
